.ONESHELL:
.PHONY: all test

SHELL=/bin/bash

all : 

# # Merge annotations for all SNVs
# data/final/all_variants_merged_annotations.tsv : data/interim/nmd_annotations.tsv \
#                                                  data/interim/cds_all_possible_snvs.vcf \
# 												 data/interim/cds_trinucleotide_contexts.tsv \
# 												 data/interim/cds_all_possible_snvs_vep_tidy.tsv \
# 												 data/interim/gnomad_v4_pass_snvs.tsv \
# 												 data/interim/mutation_rate_by_context_methyl_tidy.tsv \
# 												 src/data/observed_variants.py
# 	python3 -m src.data.observed_variants
